# Generated by Django 4.0.5 on 2022-09-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('phone_num', models.CharField(max_length=10)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketLiveScores.team')),
            ],
        ),
    ]
