# Generated by Django 4.0.5 on 2022-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketLiveScores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
