# Generated by Django 4.0.5 on 2022-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketLiveScores', '0002_alter_player_pid_alter_team_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='totalRuns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
