# Generated by Django 4.0.5 on 2022-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketLiveScores', '0003_player_wickets_player_totalruns_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='overs',
            field=models.IntegerField(default=0),
        ),
    ]
